### ISSUE TITLE
Can you add a column for active state for the non-direct peers list.

### ISSUE THREAD

**Issue by bgupta** [dlaptev/lnd_assistant#5]
Invariably most are offline. Would save time, if the list showed on/offline status.

**Comment by dlaptev** [comment]
Sorry for the late reply. I see you already closed the issue, but I will share my thoughts for completeness.

If you have a channel with some node and if you the channel shows as inactive - you can have a good guess that probably your peer is offline. But if you do not have a channel with a remote node - I am not sure how to easily check if another node is online or offline. You can maybe track when the last update message was received from a node, but this requires a much more involved integration with lnd.

If you know of a way to do that - please let me know and reopen the issue.
